# Site settings
title: openCOBRA
email: opencobra@
copyright_name: openCOBRA
github_username: openCOBRA

collections:
  packages :
  citation :
  collaborators :

# used to estimate reading time
wpm: 150

port: 4444
permalink: /:title

# jekyll-paginate
paginate: 5
paginate_path: /page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
